### ISSUE TITLE
Bot token

### ISSUE THREAD

**Issue by DasIschBims** [MegalithOffical/Blackjack-bot#2]
You have your discord bot token in the index.js, please change it on the discord developer portal and consider using something like [dotenv](https://www.npmjs.com/package/dotenv) to secure it.

**Comment by MegalithOffical** [comment]
Helllo, I know there is a token in the file but the token is reseted do its invali. Also .dotenc wont do anythink in local hosting

**Comment by DasIschBims** [comment]
Okay nice, have a good day 👍
